apiVersion: v1 
kind: PersistentVolume
metadata:
  name: medilab-mysql-pv
  namespace: medilab-db-ns #specify the namespace for your deployment
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /tmp/medilab-app-data
